Repository embeddings-benchmark/mteb, pull requests merged in 2025-03, with the labels that each got.

#2133 Add ESC50 and zero-shot classification
  mteb/abstasks/Audio/AbsTaskAudioZeroshotClassification.py
  mteb/abstasks/TaskMetadata.py
  mteb/evaluation/evaluators/Audio/ZeroshotClassificationEvaluator.py
  mteb/evaluation/evaluators/__init__.py
  mteb/models/clap_models.py
  mteb/models/overview.py
  mteb/tasks/Audio/AudioZeroshotClassification/__init__.py
  mteb/tasks/Audio/AudioZeroshotClassification/eng/ESC50.py
  mteb/tasks/Audio/__init__.py
  tests/test_benchmark/mock_models.py
  tests/test_benchmark/mock_tasks.py
  tests/test_benchmark/task_grid.py
Labels: maeb

#2269 Add unfused clap model for zero-shot
  mteb/models/clap_models.py
Labels: maeb

#2198 [v2] Refactor text tasks to use DataLoader
  mteb/abstasks/AbsTaskClassification.py
  mteb/abstasks/AbsTaskClustering.py
  mteb/abstasks/AbsTaskClusteringFast.py
  mteb/abstasks/AbsTaskMultilabelClassification.py
  mteb/create_dataloaders.py
  mteb/descriptive_stats/InstructionReranking/mFollowIR.json
  mteb/descriptive_stats/InstructionReranking/mFollowIRCrossLingual.json
  mteb/encoder_interface.py
  mteb/evaluation/__init__.py
  mteb/evaluation/evaluators/BitextMiningEvaluator.py
  mteb/evaluation/evaluators/ClassificationEvaluator.py
  mteb/evaluation/evaluators/ClusteringEvaluator.py
  mteb/evaluation/evaluators/PairClassificationEvaluator.py
  mteb/evaluation/evaluators/STSEvaluator.py
  mteb/evaluation/evaluators/SummarizationEvaluator.py
  mteb/evaluation/evaluators/__init__.py
  mteb/evaluation/evaluators/model_classes.py
  mteb/evaluation/evaluators/utils.py
  mteb/models/bedrock_models.py
  mteb/models/cohere_models.py
  mteb/models/colbert_models.py
  mteb/models/google_models.py
  mteb/models/instruct_wrapper.py
  mteb/models/jasper_models.py
  mteb/models/jina_models.py
  mteb/models/llm2vec_models.py
  mteb/models/model2vec_models.py
  mteb/models/no_instruct_sentence_models.py
  mteb/models/nomic_models.py
  mteb/models/openai_models.py
  mteb/models/promptriever_models.py
  mteb/models/repllama_models.py
  mteb/models/sentence_transformer_wrapper.py
  mteb/models/uae_models.py
  mteb/models/voyage_models.py
  mteb/models/wrapper.py
  mteb/tasks/InstructionReranking/multilingual/mFollowIR.py
  tests/test_benchmark/mock_models.py
  tests/test_benchmark/test_benchmark.py
  tests/test_evaluators/test_ClusteringEvaluator.py
Labels: v2

#2285 Add new and complete version of FSD50K multi-label audio classification task
  mteb/tasks/Audio/AudioMultilabelClassification/__init__.py
  mteb/tasks/Audio/AudioMultilabelClassification/eng/FSD50HF.py
Labels: maeb

#2284 added large, music and speech clap models
  mteb/models/clap_models.py
Labels: maeb

#2287 add AbsTaskAudioClassification, ESC50 & GunshotTriangulation datasets
  mteb/abstasks/Audio/AbsTaskAudioClassification.py
  mteb/abstasks/TaskMetadata.py
  mteb/abstasks/__init__.py
  mteb/evaluation/evaluators/Audio/ClassificationEvaluator.py
  mteb/tasks/Audio/AudioClassification/__init__.py
  mteb/tasks/Audio/AudioClassification/eng/ESC50.py
  mteb/tasks/Audio/AudioClassification/eng/GunshotTriangulation.py
  mteb/tasks/Audio/AudioMultilabelClassification/eng/FSD50HF.py
  mteb/tasks/__init__.py
Labels: maeb

#2306 Add NSynth dataset
  mteb/abstasks/TaskMetadata.py
  mteb/tasks/Audio/AudioClassification/__init__.py
  mteb/tasks/Audio/AudioClassification/eng/NSynth.py
Labels: maeb

#2292 Add urbansound8k for zero-shot
  mteb/tasks/Audio/AudioZeroshotClassification/__init__.py
  mteb/tasks/Audio/AudioZeroshotClassification/eng/UrbanSound8k.py
Labels: maeb

#2307 adding GTZAN Genre dataset
  mteb/abstasks/TaskMetadata.py
  mteb/tasks/Audio/AudioClassification/__init__.py
  mteb/tasks/Audio/AudioClassification/eng/GTZANGenre.py
Labels: maeb

#2356 Adding Beijing Opera dataset
  mteb/abstasks/TaskMetadata.py
  mteb/tasks/Audio/AudioClassification/__init__.py
  mteb/tasks/Audio/AudioClassification/eng/BeijingOpera.py
  mteb/tasks/Audio/AudioClassification/eng/VoxLingua107Top10.py
Labels: maeb

#2361 Adding Libricount dataset
  mteb/abstasks/TaskMetadata.py
  mteb/tasks/Audio/AudioClassification/__init__.py
  mteb/tasks/Audio/AudioClassification/eng/LibriCount.py
Labels: maeb

#2368 Adding Crema-D Dataset for emotion classification [HEAR]
  mteb/tasks/Audio/AudioClassification/__init__.py
  mteb/tasks/Audio/AudioClassification/eng/CREMA_D.py
Labels: maeb

#2371 Adding FSDD dataset (Free Spoken Digit Dataset)
  mteb/abstasks/TaskMetadata.py
  mteb/tasks/Audio/AudioClassification/__init__.py
  mteb/tasks/Audio/AudioClassification/eng/FSDD.py
Labels: maeb

#2294 [v2] Refactor mieb to dataloaders
  mteb/abstasks/Image/AbsTaskImageClustering.py
  mteb/create_dataloaders.py
  mteb/evaluation/evaluators/Image/Any2AnyMultiChoiceEvaluator.py
  mteb/evaluation/evaluators/Image/Any2AnyRetrievalEvaluator.py
  mteb/evaluation/evaluators/Image/Any2TextMultipleChoiceEvaluator.py
  mteb/evaluation/evaluators/Image/ClassificationEvaluator.py
  mteb/evaluation/evaluators/Image/ClusteringEvaluator.py
  mteb/evaluation/evaluators/Image/ImageTextPairClassificationEvaluator.py
  mteb/evaluation/evaluators/Image/VisualSTSEvaluator.py
  mteb/evaluation/evaluators/Image/ZeroshotClassificationEvaluator.py
  mteb/models/align_models.py
  mteb/models/blip2_models.py
  mteb/models/blip_models.py
  mteb/models/clip_models.py
  mteb/models/cohere_v.py
  mteb/models/dino_models.py
  mteb/models/e5_v.py
  mteb/models/evaclip_models.py
  mteb/models/gme_v_models.py
  mteb/models/jina_clip.py
  mteb/models/llm2clip_models.py
  mteb/models/moco_models.py
  mteb/models/nomic_models_vision.py
  mteb/models/openclip_models.py
  mteb/models/siglip_models.py
  mteb/models/vista_models.py
  mteb/models/vlm2vec_models.py
  mteb/models/voyage_v.py
  tests/test_benchmark/mock_models.py
  tests/test_benchmark/mock_tasks.py
Labels: v2

#2369 fix FSD-50K Task Metadata, Label handling and add stratified subsampling
  mteb/tasks/Audio/AudioMultilabelClassification/eng/FSD50HF.py
Labels: maeb

#2232 Add music clustering dataset
  mteb/abstasks/TaskMetadata.py
  mteb/tasks/Audio/Clustering/__init__.py
  mteb/tasks/Audio/Clustering/eng/MusicGenre.py
  mteb/tasks/Audio/Clustering/eng/VoiceGender.py
Labels: new dataset, maeb
