Repository embeddings-benchmark/mteb, pull requests merged in 2025-02, with the labels that each got.

#1924 [v2] remove `save_suffix`
  mteb/abstasks/AbsTask.py
  mteb/evaluation/MTEB.py
Labels: v2

#1995 [v2] add metadata for suppressed tasks
  mteb/descriptive_stats/BitextMining/BUCC.json
  mteb/descriptive_stats/Clustering/AlloProfClusteringP2P.json
  mteb/descriptive_stats/Clustering/AlloProfClusteringS2S.json
  mteb/descriptive_stats/Clustering/ArxivClusteringP2P.json
  mteb/descriptive_stats/Clustering/ArxivClusteringP2P.v2.json
  mteb/descriptive_stats/Clustering/ArxivClusteringS2S.json
  mteb/descriptive_stats/Clustering/BigPatentClustering.json
  mteb/descriptive_stats/Clustering/BiorxivClusteringP2P.json
  mteb/descriptive_stats/Clustering/BlurbsClusteringP2P.json
  mteb/descriptive_stats/Clustering/BlurbsClusteringS2S.json
  mteb/descriptive_stats/Clustering/CLSClusteringP2P.json
  mteb/descriptive_stats/Clustering/CLSClusteringS2S.json
  mteb/descriptive_stats/Clustering/EightTagsClustering.json
  mteb/descriptive_stats/Clustering/HALClusteringS2S.json
  mteb/descriptive_stats/Clustering/LivedoorNewsClustering.json
  mteb/descriptive_stats/Clustering/MLSUMClusteringP2P.json
  mteb/descriptive_stats/Clustering/MLSUMClusteringS2S.json
  mteb/descriptive_stats/Clustering/MedrxivClusteringP2P.json
  mteb/descriptive_stats/Clustering/MedrxivClusteringS2S.json
  mteb/descriptive_stats/Clustering/PlscClusteringP2P.json
  mteb/descriptive_stats/Clustering/PlscClusteringS2S.json
  mteb/descriptive_stats/Clustering/RedditClustering.json
  mteb/descriptive_stats/Clustering/RedditClusteringP2P.json
  mteb/descriptive_stats/Clustering/SNLClustering.json
  mteb/descriptive_stats/Clustering/StackExchangeClustering.json
  mteb/descriptive_stats/Clustering/StackExchangeClusteringP2P.json
  mteb/descriptive_stats/Clustering/SwednClustering.json
  mteb/descriptive_stats/Clustering/TenKGnadClusteringP2P.json
  mteb/descriptive_stats/Clustering/TenKGnadClusteringS2S.json
  mteb/descriptive_stats/Clustering/ThuNewsClusteringP2P.json
  mteb/descriptive_stats/Clustering/ThuNewsClusteringS2S.json
  mteb/descriptive_stats/Clustering/TwentyNewsgroupsClustering.json
  mteb/descriptive_stats/Clustering/VGClustering.json
  mteb/descriptive_stats/Retrieval/DanFEVER.json
  mteb/descriptive_stats/Retrieval/Touche2020.json
  mteb/descriptive_stats/STS/STS22.json
  mteb/descriptive_stats/Summarization/SummEvalFr.json
  tests/test_TaskMetadata.py
  tests/test_tasks/test_all_abstasks.py
Labels: v2

#2061 [MIEB] Rename classes with duplicated names
  mteb/tasks/Image/ZeroshotClassification/eng/Birdsnap.py
  mteb/tasks/Image/ZeroshotClassification/eng/Caltech101.py
  mteb/tasks/Image/ZeroshotClassification/eng/Country211.py
  mteb/tasks/Image/ZeroshotClassification/eng/DTD.py
  mteb/tasks/Image/ZeroshotClassification/eng/EuroSAT.py
  mteb/tasks/Image/ZeroshotClassification/eng/FER2013.py
  mteb/tasks/Image/ZeroshotClassification/eng/FGVCAircraft.py
  mteb/tasks/Image/ZeroshotClassification/eng/Food101.py
  mteb/tasks/Image/ZeroshotClassification/eng/GTSRB.py
  mteb/tasks/Image/ZeroshotClassification/eng/Imagenet1k.py
  mteb/tasks/Image/ZeroshotClassification/eng/MNIST.py
  mteb/tasks/Image/ZeroshotClassification/eng/OxfordPets.py
  mteb/tasks/Image/ZeroshotClassification/eng/PatchCamelyon.py
  mteb/tasks/Image/ZeroshotClassification/eng/RESISC45.py
  mteb/tasks/Image/ZeroshotClassification/eng/STL10.py
  mteb/tasks/Image/ZeroshotClassification/eng/SUN397.py
  mteb/tasks/Image/ZeroshotClassification/eng/StanfordCars.py
  mteb/tasks/Image/ZeroshotClassification/eng/UCF101.py
Labels: mieb

#2009 Add LoTTE Benchmark to MTEB
  mteb/abstasks/TaskMetadata.py
  mteb/benchmarks/benchmarks.py
  mteb/descriptive_stats/Retrieval/LoTTE.json
  mteb/models/model2vec_models.py
  mteb/tasks/Retrieval/__init__.py
  mteb/tasks/Retrieval/eng/LoTTERetrieval.py
  mteb/tasks/Retrieval/eng/__init__.py
  mteb/tasks/__init__.py
Labels: v2

#2022 Integrate Birco V2
  mteb/descriptive_stats/Reranking/BIRCO-ArguAna.json
  mteb/descriptive_stats/Reranking/BIRCO-ClinicalTrial.json
  mteb/descriptive_stats/Reranking/BIRCO-DorisMae.json
  mteb/descriptive_stats/Reranking/BIRCO-Relic.json
  mteb/descriptive_stats/Reranking/BIRCO-WTB.json
  mteb/tasks/Reranking/__init__.py
  mteb/tasks/Reranking/eng/BIRCOArguAnaReranking.py
  mteb/tasks/Reranking/eng/BIRCOClinicalTrialReranking.py
  mteb/tasks/Reranking/eng/BIRCODorisMaeReranking.py
  mteb/tasks/Reranking/eng/BIRCORelicReranking.py
  mteb/tasks/Reranking/eng/BIRCOWhatsThatBookReranking.py
  mteb/tasks/Reranking/eng/__init__.py
  mteb/tasks/__init__.py
Labels: v2

#2112 Add 2 new Static Sentence Transformer models
  mteb/models/sentence_transformers_models.py
Labels: new model
