Repository embeddings-benchmark/mteb, pull requests merged in 2025-04, with the labels that each got.

#2372 Add Language, Gender, and Age classifcation tasks based on common-language Dataset
  mteb/abstasks/TaskMetadata.py
  mteb/tasks/Audio/AudioClassification/__init__.py
  mteb/tasks/Audio/AudioClassification/eng/CommonLanguageAgeDetection.py
  mteb/tasks/Audio/AudioClassification/eng/CommonLanguageGenderDetection.py
  mteb/tasks/Audio/AudioClassification/eng/CommonLanguageLanguageClassification.py
Labels: maeb

#2472 added wavlm models
  mteb/models/overview.py
  mteb/models/wavlm_models.py
Labels: new model, maeb

#2492 [v2] Remove speed task
  Makefile
  mteb/abstasks/AbsTaskSpeedTask.py
  mteb/abstasks/__init__.py
  mteb/abstasks/the_ugly_duckling.txt
  mteb/create_meta.py
  mteb/tasks/SpeedTask/CPUSpeedTask.py
  mteb/tasks/SpeedTask/GPUSpeedTask.py
  mteb/tasks/SpeedTask/__init__.py
  mteb/tasks/__init__.py
  pyproject.toml
  tests/test_tasks/test_all_abstasks.py
Labels: v2

#2495 [v2] set default batch_size
  mteb/abstasks/AbsTask.py
  mteb/abstasks/AbsTaskBitextMining.py
  mteb/abstasks/AbsTaskClassification.py
  mteb/abstasks/AbsTaskClustering.py
  mteb/abstasks/AbsTaskClusteringFast.py
  mteb/abstasks/AbsTaskMultilabelClassification.py
  mteb/abstasks/AbsTaskRetrieval.py
  mteb/abstasks/AbsTaskSTS.py
  mteb/abstasks/Image/AbsTaskAny2AnyMultiChoice.py
  mteb/abstasks/Image/AbsTaskAny2AnyRetrieval.py
  mteb/abstasks/Image/AbsTaskImageClassification.py
  mteb/abstasks/Image/AbsTaskImageClustering.py
  mteb/abstasks/Image/AbsTaskImageMultilabelClassification.py
  mteb/abstasks/Image/AbsTaskImageTextPairClassification.py
  mteb/abstasks/Image/AbsTaskVisualSTS.py
  mteb/abstasks/Image/AbsTaskZeroShotClassification.py
  mteb/abstasks/aggregated_task.py
  mteb/evaluation/MTEB.py
  mteb/evaluation/evaluators/BitextMiningEvaluator.py
  mteb/evaluation/evaluators/ClassificationEvaluator.py
  mteb/evaluation/evaluators/ClusteringEvaluator.py
  mteb/evaluation/evaluators/Evaluator.py
  mteb/evaluation/evaluators/Image/Any2AnyMultiChoiceEvaluator.py
  mteb/evaluation/evaluators/Image/Any2AnyRetrievalEvaluator.py
  mteb/evaluation/evaluators/Image/ClassificationEvaluator.py
  mteb/evaluation/evaluators/Image/ClusteringEvaluator.py
  mteb/evaluation/evaluators/Image/ImageTextPairClassificationEvaluator.py
  mteb/evaluation/evaluators/Image/VisualSTSEvaluator.py
  mteb/evaluation/evaluators/Image/ZeroShotClassificationEvaluator.py
  mteb/evaluation/evaluators/PairClassificationEvaluator.py
  mteb/evaluation/evaluators/RetrievalEvaluator.py
  mteb/evaluation/evaluators/STSEvaluator.py
  mteb/evaluation/evaluators/SummarizationEvaluator.py
  mteb/evaluation/evaluators/model_classes.py
  tests/test_evaluators/test_ClusteringEvaluator.py
  tests/test_evaluators/test_InstructionRetrievalEvaluator.py
  tests/test_evaluators/test_RetrievalEvaluator.py
Labels: v2

#2569 Docs: Improve MIEB docs
  README.md
  docs/mieb/readme.md
  mteb/benchmarks/benchmarks.py
Labels: mieb

#2561 fix: Add Encodechka benchmark
  mteb/abstasks/TaskMetadata.py
  mteb/benchmarks/benchmarks.py
  mteb/tasks/Classification/__init__.py
  mteb/tasks/Classification/rus/InappropriatenessClassification.py
  mteb/tasks/Classification/rus/ru_nlu_intent_classification.py
  mteb/tasks/Classification/rus/ru_toixic_classification_okmlcup.py
  mteb/tasks/Classification/rus/senti_ru_eval.py
  mteb/tasks/MultiLabelClassification/__init__.py
  mteb/tasks/MultiLabelClassification/rus/ru_toixic_multilabelclassification_okmlcup.py
  mteb/tasks/STS/rus/RuSTSBenchmarkSTS.py
Labels: new benchmark

#2601 [v2] Refactor retrieval dataload
  mteb/abstasks/AbsTaskRetrieval.py
  mteb/abstasks/dataloaders.py
  mteb/abstasks/dataset_loaders.py
Labels: v2
