Repository embeddings-benchmark/mteb, pull requests merged in 2025-10, with the labels that each got.

#3214 dataset: add human tasks and benchmark
  mteb/benchmarks/benchmarks/__init__.py
  mteb/benchmarks/benchmarks/benchmarks.py
  mteb/leaderboard/benchmark_selector.py
  mteb/load_results/load_results.py
  mteb/model_meta.py
  mteb/models/human.py
  mteb/models/overview.py
  mteb/tasks/Classification/__init__.py
  mteb/tasks/Classification/eng/HUMEEmotionClassification.py
  mteb/tasks/Classification/eng/HUMEToxicConversationsClassification.py
  mteb/tasks/Classification/eng/HUMETweetSentimentExtractionClassification.py
  mteb/tasks/Classification/multilingual/HUMEMultilingualSentimentClassification.py
  mteb/tasks/Classification/multilingual/MultilingualSentimentClassification.py
  mteb/tasks/Clustering/__init__.py
  mteb/tasks/Clustering/eng/HUMEArxivClusteringP2P.py
  mteb/tasks/Clustering/eng/HUMERedditClusteringP2P.py
  mteb/tasks/Clustering/eng/HUMEWikiCitiesClustering.py
  mteb/tasks/Clustering/multilingual/HUMESIB200ClusteringS2S.py
  mteb/tasks/Reranking/__init__.py
  mteb/tasks/Reranking/eng/HUMECore17InstructionReranking.py
  mteb/tasks/Reranking/eng/HUMENews21InstructionReranking.py
  mteb/tasks/Reranking/eng/HUMERobust04InstructionReranking.py
  mteb/tasks/Reranking/multilingual/HUMEWikipediaRerankingMultilingual.py
  mteb/tasks/STS/__init__.py
  mteb/tasks/STS/eng/HUMESICKR.py
  mteb/tasks/STS/eng/HUMESTS12.py
  mteb/tasks/STS/eng/HUMESTSBenchmark.py
  mteb/tasks/STS/multilingual/HUMESTS22.py
  tests/test_TaskMetadata.py
Labels: new benchmark

#3231 Feat: Move zero-shot percentage calculation to the end of summary
  mteb/benchmarks/_create_table.py
  mteb/leaderboard/app.py
  mteb/leaderboard/table.py
Labels: leaderboard

#3180 [v2] fix issues when loading results
  .github/workflows/docs.yml
  .github/workflows/documentation.yml
  .github/workflows/leaderboard_build.yml
  mteb/models/model_meta.py
  mteb/results/task_result.py
Labels: v2, stale

#3267 [v2] fix ci
  .github/workflows/docs.yml
  .github/workflows/documentation.yml
  mteb/benchmarks/benchmarks/benchmarks.py
  mteb/leaderboard/app.py
Labels: v2

#3288 [v2] Make co2 optioinal
  mteb/MTEB.py
Labels: v2

#3293 Reupload last datasets with `trust_remote_code`
  mteb/tasks/BitextMining/multilingual/BUCCBitextMining.py
  mteb/tasks/Classification/eng/PoemSentimentClassification.py
  mteb/tasks/Clustering/fra/AlloProfClusteringS2S.py
  mteb/tasks/Clustering/swe/swedn_clustering.py
Labels: v2
