Repository embeddings-benchmark/mteb, pull requests merged in 2025-06, with the labels that each got.

#2751 MAEB: Seamlessm4t Model (V2)
  mteb/models/overview.py
  mteb/models/seamlessm4t_models.py
Labels: maeb

#2757 [MAEB] CNN14 Model (PANNs)
  mteb/models/cnn14_model.py
  mteb/models/overview.py
  pyproject.toml
Labels: maeb

#2753 MAEB: M-CTC-T Model
  mteb/models/mctct_model.py
  mteb/models/overview.py
Labels: maeb

#2653 Added GTZAN Clustering Dataset
  mteb/tasks/Audio/Clustering/__init__.py
  mteb/tasks/Audio/Clustering/eng/GTZANGenreClustering.py
Labels: maeb

#2642 Added AmbientAcousticContext Dataset
  mteb/tasks/Audio/AudioClassification/__init__.py
  mteb/tasks/Audio/AudioClassification/eng/AmbientAcousticContext.py
  mteb/tasks/Audio/Clustering/__init__.py
  mteb/tasks/Audio/Clustering/eng/AmbientAcousticContextClustering.py
Labels: maeb

#2654 Added VoxCeleb Clustering Dataset
  mteb/abstasks/TaskMetadata.py
  mteb/tasks/Audio/Clustering/__init__.py
  mteb/tasks/Audio/Clustering/eng/VoxCelebClustering.py
Labels: maeb

#2463 Added 5 datasets for audio pair classification
  mteb/abstasks/Audio/AbsTaskAudioPairClassification.py
  mteb/abstasks/Audio/AbsTaskAudioReranking.py
  mteb/descriptive_stats/BitextMining/WebFAQBitextMiningQAs.json
  mteb/descriptive_stats/BitextMining/WebFAQBitextMiningQuestions.json
  mteb/evaluation/evaluators/Audio/AudioRerankingEvaluator.py
  mteb/models/wav2vec2_models.py
  mteb/tasks/Audio/AudioPairClassification/__init__.py
  mteb/tasks/Audio/AudioPairClassification/eng/CREMAD.py
  mteb/tasks/Audio/AudioPairClassification/eng/ESC50.py
  mteb/tasks/Audio/AudioPairClassification/eng/NMSQA.py
  mteb/tasks/Audio/AudioPairClassification/eng/VocalSound.py
  mteb/tasks/Audio/AudioPairClassification/eng/VoxPopuliAccent.py
  mteb/tasks/Audio/Clustering/__init__.py
  mteb/tasks/Audio/__init__.py
Labels: maeb

#2782 Update issue and pr templates
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/enhancement.yaml
  .github/ISSUE_TEMPLATE/new_dataset.yaml
  .github/ISSUE_TEMPLATE/new_model.yaml
  .github/pull_request_template.md
Labels: enhancement

#2641 Added Birdclef Subset Dataset
  mteb/models/wavlm_models.py
  mteb/tasks/Audio/AudioClassification/__init__.py
  mteb/tasks/Audio/AudioClassification/eng/BirdCLEF.py
Labels: maeb

#2742 model: add ListConRanker model
  mteb/models/listconranker.py
  mteb/models/overview.py
Labels: new model
